### ISSUE TITLE
LDAP tree representation as nested dict() 

### ISSUE THREAD

**Issue by zopyx** [bluedynamics/node.ext.ldap#17]
It would be nice having as representation of an LDAPNode and its subtree as nested dict via a dedicated method as_tree(). There is already a traverser via printtree().  Of course such a method has the potential to act as a memory bomb for large subtrees. The goal would be having a tree data structure that could be serialized to JSON.

**Comment by rnixx** [comment]
JSON serialization would be a nice feature. Since node.ext.ldap "just" implements general contracts from node package, I think this would be the right place for a JSON serializer. Memory issues could be disarmed to a certain degree when using generators for serialization iteration which can easily be aborted.

**Comment by rnixx** [comment]
I Added basic JSON serialization here https://github.com/bluedynamics/node/blob/master/src/node/serializer.py (docs -> https://github.com/bluedynamics/node/blob/master/src/node/serializer.rst)

And tried it out with LDAPNodes here https://github.com/bluedynamics/node.ext.ldap/blob/master/README.rst#json-serialization

There's probably the need of an attributes and children blacklist mechanism, but that's not implemented yet.
