### ISSUE TITLE
How to properly optimize the amount of different LDAP queries required

### ISSUE THREAD

**Issue by datakurre** [bluedynamics/node.ext.ldap#18]
The most complex and controversial refactoring I had to make to get node.ext.ldap working with a large local (or just with any remote ldap) was to optimize the amount LDAP queries it does. My approach was to normalize searches so that there was only one different search for each object.

https://github.com/datakurre/node.ext.ldap/commits/master

Any ideas, how that should be done more properly? Mainly
- I needed to store configured attribute mapping somewhere (search_attrlist) and enforce each query to use that (instead of only what the actual need was or instead of current "*" for attribute sheet)
- Instead of looking up nodes with root base DN and queryFilter at first and then with direct DN, I required to store queryFilter (search_criteria) and enforce use it instead of direct DN (slower LDAP query as direct DN as such, but because search was always made anyway, the search was already available in cache)

**Comment by rnixx** [comment]
The approach for normalizing the query looks good to me.

Currently there are 3 queries for ``LDAPNode`` objects. In ``LDAPNode.__iter__``, ``LDAPNode.__getitem__`` and ``LDAPNodeAttributes.load``

Maybe it would make sense to use the normalized query in ``__getitem__``, store the search result on the node and refactor ``LDAPNodeAttributes`` to avoid querying the directory again (the node is accessible via ``self.parent``). This would reduce the searches significantly in the first place.

I'm not really convinced yet whether I like the use of the normalized query on ``__iter__``. How often is ``__iter__`` used in the context of pas.plugins.ldap?

**Comment by datakurre** [comment]
Thanks.

I should be able to return on this next week. Probably __iter__ could be refactored out.

**Comment by rnixx** [comment]
After some rethinking I'm of the mind we need to be able to configure whether the complete entries should already be fetched at ``__iter__`` time or not, so we can experiment with the different behaviours a little bit referring speed, memory footprint and resulting subsequent queries.

The normalized query in ``__iter__`` as implemented in your branch is only effective in conjunction with caching, because subsequent queries happen anyway when accessing the nodes. So we have this options:

* Add a dedicated config flag whether to normalize queries on ``__iter__``.
* Normalize the query on ``__iter__`` only if caching is enabled (Currently my preferred variant).
* Remember the search result on ``__iter__`` to avoid subsequent queries already on ``__getitem__``. But this actually is just another form of caching, and may be a downside in memory consumption.

Nevertheless the separate query on accessing node attributes can be avoided entirely by fetching all attributes of interest in ``__getitem__``, remembering the result on the node object and use it in ``LDAPNodeAttributes``.

**Comment by jensens** [comment]
The base idea to keep __iter__ queries simple and it answers small is because if one has 10000 users and iterates over it to get to a batch from 9000 - 9999 we would need to fetch all 9099 entries complete which is expensive.

Also the tree in memory gets larger than needed.

To optimize this we would have to implement slicing and then iterate over the slice, so we can write ``users[9000:9099]`` and then we can iterate low-cost to 8999 (because LDAP/pyhon-LDAP does not support slicing/batch-request) and then fetch full entries to avoid query each twice.

The most difficult part is to change PAS to use it in an efficient way.

**Comment by datakurre** [comment]
Agreed. I should be able to return to this in the middle of next week.

**Comment by rnixx** [comment]
closing this in favor of #37
