### ISSUE TITLE
UnicodeWarning

### ISSUE THREAD

**Issue by zopyx** [bluedynamics/node.ext.ldap#19]
I am receiving this warning likely because my query are encoded as str rather and unicode.
I assume you want to check or enforce unicode parameters here? I would prefer having an API with strong parameter checks instead of praying that a query will work with unicode strings and/or utf8 encoded strings.

/home/ajung/sandboxes/unimr.staff/eggs/node.ext.ldap-1.0b3-py2.7.egg/node/ext/ldap/session.py:52: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if queryFilter in ('', u'', None):

**Comment by rnixx** [comment]
This relates to https://github.com/bluedynamics/node.ext.ldap/issues/16. All the auto encoding/decoding functionality turned out to be really CPU consuming and the goal in the long run is to handle data binary only inside node.ext.ldap, with a config flag whether to keep the old bahavior for b/c reasons.

The warning results from checking queryFilter against a list containing an empty unicode and an empty regular string.

I wonder whether we can just check for ``if not queryFilter``, since the query filter should always be a string (maybe it can be an instance of ``LDAPFilter``, if so we'd need to implement ``__nonzero__`` on it)

**Comment by zopyx** [comment]
the old behavior is support utf8 and unicode, the desired behavior is to support unicode only?
I am currently writing on a new module so I want to know what the right way will be way in the future.

**Comment by rnixx** [comment]
First of all, the test suite runs and the warning is gone with the modified check here https://github.com/bluedynamics/node.ext.ldap/commit/74ff49545ed6b9dc7081c0989ec851019df85fc2.

LDAP by default works with UTF-8 encoded data and node.ext.ldap by default converts this data to unicode.

The new behaviour in the future should support non-auto-encoding/decoding, so all data is available as UTF-8 encoded strings inside node.ext.ldap, but this should not be the default in the first place.

If you use something like safe_encode/safe_decode in your node.ext.ldap using module, you should be safe, even if described behaviour becomes the default somewhen.

**Comment by rnixx** [comment]
reopen please if there is anything left.

**Comment by rnixx** [comment]
UPDATE: well, actually my claim why the UnicodeWarning has been logged is wrong, anyway the referenced commit fixes the issue.

The warning happens if you try to compare a UTF-8 encoded string which cannot be converted with a unicode cast without encoding:

    >>> s = u'a'.encode('utf-8')
    >>> s == u'a'
    True

    >>> s = u'ä'.encode('utf-8')
    >>> s == u'ä'
    __main__:1: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
    False
